version: '3.8'

services:
  # Redis Cache for Development
  redis:
    image: redis:7-alpine
    container_name: puppytalk-redis-dev
    restart: unless-stopped
    command: redis-server --requirepass ""
    ports:
      - "6379:6379"
    volumes:
      - redis_dev_data:/data
    networks:
      - puppytalk-dev-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      timeout: 10s
      retries: 5
      interval: 30s

  # MySQL Database for Development
  mysql:
    image: mysql:8.0
    container_name: puppytalk-mysql-dev
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: puppytalk
      MYSQL_USER: puppytalk
      MYSQL_PASSWORD: puppytalk123
    ports:
      - "3306:3306"
    volumes:
      - mysql_dev_data:/var/lib/mysql
      - ./docker/mysql/conf.d:/etc/mysql/conf.d:ro
    networks:
      - puppytalk-dev-network
    command: >
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --default-time-zone='+09:00'
      --sql-mode=STRICT_TRANS_TABLES,NO_ZERO_DATE,NO_ZERO_IN_DATE,ERROR_FOR_DIVISION_BY_ZERO

  # PuppyTalk Development Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: puppytalk-app-dev
    restart: unless-stopped
    depends_on:
      - mysql
      - redis
    environment:
      # Spring Profile for Development
      SPRING_PROFILES_ACTIVE: docker
      
      # Database Configuration
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: puppytalk
      DB_USERNAME: puppytalk
      DB_PASSWORD: puppytalk123
      
      # Redis Configuration
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: ""
      
      # JWT Configuration
      JWT_SECRET: puppytalk-dev-secret-key-for-jwt-token-generation-minimum-256-bits
      
      # JVM Options for Development
      JAVA_OPTS: "-Xmx512m -Xms256m -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
    ports:
      - "8081:8080"
      - "5005:5005"  # Debug port
    networks:
      - puppytalk-dev-network
    volumes:
      # Hot reload for development (optional)
      - ./puppytalk-bootstrap/src:/app/src:ro

volumes:
  mysql_dev_data:
    driver: local
  redis_dev_data:
    driver: local

networks:
  puppytalk-dev-network:
    driver: bridge