spring:
  profiles:
    active: local
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

# Inactivity Notification Scheduler Configuration
inactivity:
  scheduler:
    enabled: ${INACTIVITY_SCHEDULER_ENABLED:true}

# AI Multi-Provider Configuration
ai:
  default-provider: ${AI_DEFAULT_PROVIDER:gpt-oss}
  default-model: ${AI_DEFAULT_MODEL:gpt-oss:20b}
  max-tokens: ${AI_MAX_TOKENS:150}
  temperature: ${AI_TEMPERATURE:0.8}
  fallback-providers: ${AI_FALLBACK_PROVIDERS:openai,claude}

  providers:
    # gpt-oss (Local Model via Ollama)
    gpt-oss:
      enabled: ${AI_GPT_OSS_ENABLED:true}
      server-url: ${AI_GPT_OSS_SERVER_URL:http://localhost:11434}
      timeout: ${AI_GPT_OSS_TIMEOUT:30}

    # OpenAI ChatGPT
    openai:
      enabled: ${AI_OPENAI_ENABLED:false}
      api-key: ${AI_OPENAI_API_KEY:}
      base-url: ${AI_OPENAI_BASE_URL:https://api.openai.com}
      timeout: ${AI_OPENAI_TIMEOUT:30}

    # Anthropic Claude
    claude:
      enabled: ${AI_CLAUDE_ENABLED:false}
      api-key: ${AI_CLAUDE_API_KEY:}
      base-url: ${AI_CLAUDE_BASE_URL:https://api.anthropic.com}
      timeout: ${AI_CLAUDE_TIMEOUT:30}

    # Google Gemini
    gemini:
      enabled: ${AI_GEMINI_ENABLED:false}
      api-key: ${AI_GEMINI_API_KEY:}
      base-url: ${AI_GEMINI_BASE_URL:https://generativelanguage.googleapis.com}
      timeout: ${AI_GEMINI_TIMEOUT:30}

---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/puppy_talk_db?useSSL=false&allowPublicKeyRetrieval=true}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:1234}
    driver-class-name: com.mysql.cj.jdbc.Driver

---
spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://mysql:3306/puppy_talk_db?useSSL=false&allowPublicKeyRetrieval=true}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:1234}
    driver-class-name: com.mysql.cj.jdbc.Driver

---
spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true